version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: formbuilder
      MYSQL_USER: formbuilder
      MYSQL_PASSWORD: formbuilder
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  formbuilderapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Sql=Server=mysql;Database=formbuilder;User=formbuilder;Password=formbuilder;
      - MongoDb__ConnectionString=mongodb://mongodb:27017
      - MongoDb__DatabaseName=formbuilder
    depends_on:
      - mysql
      - mongodb

volumes:
  mysql-data:
  mongodb-data: